# Programming Assignment 5.2

In [7]:
from sklearn.decomposition import PCA
import numpy as np
import pandas 
import scipy

Загрузите данные close_prices.csv. В этом файле приведены цены акций 30 компаний на закрытии торгов за каждый день периода.

In [60]:
close = pandas.read_csv('close.csv')
close.head()

,date,AXP,BA,CAT,CSCO,CVX,DD,DIS,GE,GS,...,PFE,PG,T,TRV,UNH,UTX,V,VZ,WMT,XOM
0,2013-09-23,76.440002,117.510002,85.029999,24.270000,125.519997,59.409999,64.750000,24.280001,165.250000,...,28.799999,79.279999,34.220001,86.379997,71.820000,109.419998,196.240005,47.980000,76.419998,87.750000
1,2013-09-24,76.070000,119.000000,85.110001,24.139999,124.489998,59.319997,64.320000,24.320000,162.970001,...,28.709999,78.620003,34.090000,85.870003,72.320000,110.000000,193.339996,47.270000,75.750000,87.360001
2,2013-09-25,75.989998,118.510002,84.500000,24.430000,124.070000,59.319997,64.449997,24.230000,162.309998,...,28.490000,77.720001,34.049999,85.980003,71.980003,109.260002,191.559998,46.950001,74.650002,87.139999
3,2013-09-26,76.320000,119.379997,84.199997,23.770000,123.489998,59.509996,65.239998,24.250000,162.289993,...,28.520000,78.050003,34.230000,85.830002,72.160004,109.660004,193.559998,47.669998,74.620003,87.070000
4,2013-09-27,75.889999,118.739998,83.800003,23.330000,122.639999,59.009995,65.190002,24.049999,159.850006,...,28.879999,77.209999,33.980000,85.410004,71.989998,109.360001,193.050003,47.000000,74.360001,86.900002

На загруженных данных обучите преобразование PCA с числом компоненты равным 10. Скольких компонент хватит, чтобы объяснить 90% дисперсии?

In [29]:
pca_close = PCA(n_components=10)
pca_close.fit_transform(close.iloc[:, 1:])
print(pca_close.explained_variance_ratio_) 
np.sum(pca_close.explained_variance_ratio_[:4])
# 4 компоненты

components = pca_close.components_
print components.shape

[ 0.73897118  0.11007169  0.04995088  0.0287492   0.02215448  0.01931577
  0.00674853  0.00614091  0.00320594  0.00305611]
(10, 30)

(374, 10)

Примените построенное преобразование к исходным данным и возьмите значения первой компоненты.

In [40]:
transformed = pca_close.transform(close.iloc[:, 1:])
first_component = transformed[:, 0]
print first_component.shape

(374,)

Загрузите информацию об индексе Доу-Джонса из файла djia_index.csv. Чему равна корреляция Пирсона между первой компонентой и индексом Доу-Джонса?

In [41]:
dow = pandas.read_csv('dja.csv')

scipy.stats.pearsonr(dow.iloc[:,1], first_component)

(0.90965221930502371, 5.1928879052168097e-144)

Какая компания имеет наибольший вес в первой компоненте? Укажите ее название с большой буквы.

In [66]:
components = pca_close.components_

np.where( components[0] == max(abs(components[0])) )

close[[27]]

              V
0    196.240005
1    193.339996
2    191.559998
3    193.559998
4    193.050003
5    191.100006
6    193.220001
7    191.820007
8    188.649994
9    190.479996
10   186.330002
11   182.529999
12   183.850006
13   189.029999
14   192.199997
15   193.440002
16   191.369995
17   195.630005
18   198.279999
19   200.449997
20   200.039993
21   199.979996
22   198.889999
23   202.910004
24   203.059998
25   203.080002
26   204.240005
27   203.820007
28   196.669998
29   199.160004
..          ...
344  264.890015
345  271.799988
346  267.420013
347  265.459991
348  264.549988
349  265.989990
350  270.910004
351  269.630005
352  270.869995
353  269.119995
354  269.100006
355  273.000000
356  273.010010
357  272.470001
358  273.010010
359  273.750000
360  271.309998
361  278.290009
362  275.299988
363  273.750000
364  274.130005
365  269.339996
366  271.420013
367  265.200012
368  264.750000
369  269.579987
370  265.029999
371  269.019989
372  264.500000
373  267.670013

[374 rows x 1 columns]